export default {
  id: "merlin",
  priority: 222,
  alias: "merlin",
  aliases: [
    "mer",
  ],
  uiAlias: "mer",
  display: {
    name: "Merlin AI (Pro)",
    icon: "auto_awesome",
    color: "#6D28D9",
    textIcon: "ME",
    website: "https://www.getmerlin.in",
    notice: {
      text: "Paste your getmerlin.in access token — the 'Authorization: Bearer ...' value from a logged-in request (DevTools → Network → any /arcane request). Token expires ~1h; re-paste when it stops working.",
      apiKeyUrl: "https://www.getmerlin.in/chat",
    },
  },
  category: "webCookie",
  authType: "cookie",
  authHint: "Paste your getmerlin.in Pro account Bearer access token (expires ~1h).",
  transport: {
    baseUrl: "https://www.getmerlin.in/arcane/api/v2/thread/unified",
    format: "merlin",
    authType: "cookie",
  },
  models: [
    { id: "minimax-m2.7", name: "MiniMax M2.7 (via Merlin)" },
    { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite (via Merlin)" },
    { id: "gemini-3.1-flash-lite", name: "Gemini 3.1 Flash Lite (via Merlin)" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash (via Merlin)" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro (via Merlin)" },
    { id: "gpt-5.4", name: "GPT 5.4 (via Merlin)" },
    { id: "gpt-5.5", name: "GPT 5.5 (via Merlin)" },
    { id: "claude-4.5-haiku", name: "Claude Haiku 4.5 (via Merlin)" },
    { id: "claude-4.6-sonnet", name: "Claude Sonnet 4.6 (via Merlin)" },
    { id: "claude-4.8-opus", name: "Claude Opus 4.8 (via Merlin)" },
    { id: "grok-4.3", name: "Grok 4.3 (via Merlin)" },
    { id: "kimi-k2.6", name: "Kimi K2.6 (via Merlin)" },
    { id: "deepseek-v4-pro", name: "DeepSeek v4 Pro (via Merlin)" },
    { id: "glm-5.1", name: "GLM 5.1 (via Merlin)" },
  ],
  serviceKinds: ["llm"],
};
