export default {
  id: "notion",
  priority: 285,
  alias: "nt",
  uiAlias: "nt",
  display: {
    name: "Notion",
    icon: "description",
    color: "#111111",
    textIcon: "NT",
    website: "https://www.notion.so/",
    notice: {
      text: "Dual auth: connect via OAuth to enable Notion's Remote MCP tools (search, fetch, create pages, databases) in VS Code/OpenCode, AND/OR paste your Notion AI session cookie (token_v2 + notion_user_id) to chat with Opus/GPT/Gemini models with tool calling.",
      signupUrl: "https://www.notion.so/",
    },
  },
  category: "oauth",
  authModes: ["oauth", "apikey"],
  authType: "cookie",
  authHint: "For chat models: paste full cookie from app.notion.com (must include token_v2 and notion_user_id). For tools only: use OAuth.",
  hasOAuth: true,
  hasProviderSpecificData: true,
  serviceKinds: ["llm", "tools"],
  models: [
    { id: "notion-ai", name: "Notion AI (Default)" },
    { id: "opus-4.8", name: "Claude Opus 4.8" },
    { id: "opus-4.7", name: "Claude Opus 4.7" },
    { id: "opus-4.6", name: "Claude Opus 4.6" },
    { id: "sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.2", name: "GPT-5.2" },
    { id: "gemini-3-flash", name: "Gemini 3 Flash" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
  ],
  passthroughModels: true,
};