"use server";

import { NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";
import os from "os";
import { parseJSONC } from "confbox";
import { findModelName } from "open-sse/config/providerModels.js";
import { getCopilotModelLimits } from "@/shared/utils/copilotModelLimits.js";
import { supportsCopilotVisionWithCombos } from "@/shared/utils/copilotModelCapabilities.js";
import { expandCopilotReasoningVariants } from "@/shared/utils/copilotReasoningVariants.js";
import { getCombos, getSettings, updateSettings } from "@/lib/localDb";
import {
  applyCopilotByokUtilitySettings,
  buildCopilotAuthorizationHeaders,
} from "./copilotConfig.mjs";

// Resolve chatLanguageModels.json path per OS
const getConfigPath = () => {
  const home = os.homedir();
  const platform = os.platform();
  if (platform === "win32") {
    return path.join(process.env.APPDATA || home, "Code", "User", "chatLanguageModels.json");
  }
  if (platform === "darwin") {
    return path.join(home, "Library", "Application Support", "Code", "User", "chatLanguageModels.json");
  }
  return path.join(home, ".config", "Code", "User", "chatLanguageModels.json");
};

// Resolve VS Code User settings.json path per OS (same folder as chatLanguageModels.json)
const getVscodeUserSettingsPath = () => {
  const home = os.homedir();
  const platform = os.platform();
  if (platform === "win32") {
    return path.join(process.env.APPDATA || home, "Code", "User", "settings.json");
  }
  if (platform === "darwin") {
    return path.join(home, "Library", "Application Support", "Code", "User", "settings.json");
  }
  return path.join(home, ".config", "Code", "User", "settings.json");
};

// Safely read VS Code settings.json (JSONC: comments + trailing commas + URLs).
// Returns { settings, parsable, existed }:
//  - existed=false: file is missing (safe to create fresh)
//  - parsable=false: file exists but can't be parsed — callers MUST NOT overwrite
//    it, otherwise the user's entire settings.json would be destroyed.
const readVscodeUserSettings = async () => {
  const filePath = getVscodeUserSettingsPath();
  let content;
  try {
    content = await fs.readFile(filePath, "utf-8");
  } catch (error) {
    if (error.code === "ENOENT") return { settings: {}, parsable: true, existed: false };
    throw error;
  }
  if (!content.trim()) return { settings: {}, parsable: true, existed: true };
  try {
    const parsed = parseJSONC(content);
    return { settings: parsed && typeof parsed === "object" ? parsed : {}, parsable: true, existed: true };
  } catch {
    return { settings: null, parsable: false, existed: true };
  }
};

// VS Code's direct chat.utilityModel overrides do not resolve custom-endpoint
// groups reliably. Let background utility tasks follow the selected BYOK agent
// instead, and remove stale direct overrides generated by older 9Router builds.
const applyUtilityModelsToVscode = async (utilityModel, utilitySmallModel) => {
  const { settings, parsable, existed } = await readVscodeUserSettings();
  if (!parsable) return { applied: false, reason: "unparsable" };

  const enabled = Boolean(utilityModel?.trim() || utilitySmallModel?.trim());
  const next = applyCopilotByokUtilitySettings(settings, enabled);
  const changed = JSON.stringify(next) !== JSON.stringify(settings);

  if (!changed && existed) return { applied: true, changed: false };

  const filePath = getVscodeUserSettingsPath();
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, JSON.stringify(next, null, 2));
  return { applied: true, changed: true };
};

const readConfig = async () => {
  try {
    const content = await fs.readFile(getConfigPath(), "utf-8");
    // Tolerate JSONC (trailing commas) and treat unparseable files as "no config"
    // rather than throwing a 500 that the UI misreads as "tool not installed".
    const stripped = content.replace(/,(\s*[}\]])/g, "$1");
    return JSON.parse(stripped);
  } catch (error) {
    return null;
  }
};

const has9RouterConfig = (config) => {
  if (!Array.isArray(config)) return false;
  return config.some((entry) => entry.name === "9Router");
};

const get9RouterEntry = (config) => {
  if (!Array.isArray(config)) return null;
  return config.find((entry) => entry.name === "9Router") || null;
};

const getModelParts = (id) => {
  if (typeof id !== "string") return { alias: "", modelId: "" };
  const slash = id.indexOf("/");
  if (slash <= 0) return { alias: "", modelId: id };
  return { alias: id.slice(0, slash), modelId: id.slice(slash + 1) };
};

const resolveModelDisplayName = (id, modelNames = {}) => {
  const requested = typeof modelNames?.[id] === "string" ? modelNames[id].trim() : "";
  if (requested) return requested;

  const { alias, modelId } = getModelParts(id);
  if (alias && modelId) {
    const name = findModelName(alias, modelId);
    if (name && name !== modelId) return name;
  }
  return id;
};

// GET - Read current copilot config
export async function GET() {
  try {
    const config = await readConfig();
    const entry = get9RouterEntry(config);
    const settings = await getSettings().catch(() => ({}));
    const visionFallbackModels = Array.isArray(settings?.visionFallbackModels) ? settings.visionFallbackModels : [];
    const copilotUtilityModel = typeof settings?.copilotUtilityModel === "string" ? settings.copilotUtilityModel : "";
    const copilotUtilitySmallModel = typeof settings?.copilotUtilitySmallModel === "string" ? settings.copilotUtilitySmallModel : "";

    return NextResponse.json({
      installed: true,
      config,
      has9Router: has9RouterConfig(config),
      configPath: getConfigPath(),
      currentModel: entry?.models?.[0]?.id || null,
      currentUrl: entry?.models?.[0]?.url || null,
      visionFallbackModels,
      copilotUtilityModel,
      copilotUtilitySmallModel,
    });
  } catch (error) {
    console.log("Error checking copilot settings:", error);
    return NextResponse.json({ error: "Failed to check copilot settings" }, { status: 500 });
  }
}

// Ensure the base URL targets the /v1 API root. The UI always sends ".../v1",
// but direct API callers may pass a bare origin — without this, the generated
// endpoint would be "<origin>/chat/completions", which the Next app 404s.
const normalizeCopilotBaseUrl = (baseUrl) => {
  const url = String(baseUrl || "").trim().replace(/\/+$/, "");
  return /\/v1$/.test(url) ? url : `${url}/v1`;
};

// POST - Apply 9Router config to chatLanguageModels.json
export async function POST(request) {
  try {
    const { baseUrl, apiKey, models, modelNames = {}, modelContextSizes = {}, visionFallbackModels, utilityModel = "", utilitySmallModel = "" } = await request.json();

    if (!baseUrl || !models?.length) {
      return NextResponse.json({ error: "baseUrl and models are required" }, { status: 400 });
    }

    // Persist vision-fallback relay list to settings so the server can delegate
    // image understanding at request time. When any fallback is configured,
    // every model must advertise vision:true in the VS Code config below —
    // otherwise VS Code strips images before they ever reach 9Router.
    let fallbackActive = false;
    if (Array.isArray(visionFallbackModels)) {
      const cleaned = visionFallbackModels.filter((m) => typeof m === "string" && m.trim()).map((m) => m.trim());
      fallbackActive = cleaned.length > 0;
      await updateSettings({ visionFallbackModels: cleaned }).catch((e) => {
        console.log("Failed to persist visionFallbackModels:", e);
      });
    } else {
      const settings = await getSettings().catch(() => ({}));
      fallbackActive = Array.isArray(settings?.visionFallbackModels) && settings.visionFallbackModels.length > 0;
    }

    const configPath = getConfigPath();
    await fs.mkdir(path.dirname(configPath), { recursive: true });

    // Read existing config array
    let config = [];
    try {
      const existing = await fs.readFile(configPath, "utf-8");
      const parsed = JSON.parse(existing);
      config = Array.isArray(parsed) ? parsed : [];
    } catch { /* No existing config */ }

    const endpointUrl = `${normalizeCopilotBaseUrl(baseUrl)}/chat/completions`;
    const keyToUse = apiKey || "sk_9router";

    const combos = await getCombos().catch(() => []);

    const baseModels = models.map((id) => ({
      id,
      name: resolveModelDisplayName(id, modelNames),
      url: endpointUrl,
      apiType: "chat-completions",
      // VS Code 1.129 does not consistently propagate the provider-level key
      // to per-model Custom Endpoint requests. Explicitly wire the auth header;
      // this is required remotely because loopback-only auth bypass no longer
      // applies through Tailscale/Cloudflare.
      requestHeaders: buildCopilotAuthorizationHeaders(keyToUse),
      toolCalling: true,
      // Advertise vision when the model (or any combo member) natively supports
      // it OR a vision-fallback relay is configured (so VS Code forwards images
      // for 9Router to delegate). Combo-aware so bare combo names like
      // "opus-4.8" inherit their members' vision capability.
      vision: supportsCopilotVisionWithCombos(id, combos) || fallbackActive,
      ...getCopilotModelLimits(id, modelContextSizes?.[id], combos),
    }));

    const newEntry = {
      name: "9Router",
      vendor: "customendpoint",
      apiKey: keyToUse,
      apiType: "chat-completions",
      models: expandCopilotReasoningVariants(baseModels, combos),
    };

    // Replace existing 9Router entry or append
    const idx = config.findIndex((e) => e.name === "9Router");
    if (idx >= 0) {
      config[idx] = newEntry;
    } else {
      config.push(newEntry);
    }

    await fs.writeFile(configPath, JSON.stringify(config, null, 2));

    // Persist utility-model selections and mirror them into VS Code settings.json
    // (chat.utilityModel / chat.utilitySmallModel). BYOK setups have no built-in
    // Copilot utility model, so these power title generation, commit messages,
    // intent detection, and other lightweight background tasks.
    const utilityModelClean = typeof utilityModel === "string" ? utilityModel.trim() : "";
    const utilitySmallModelClean = typeof utilitySmallModel === "string" ? utilitySmallModel.trim() : "";
    await updateSettings({
      copilotUtilityModel: utilityModelClean,
      copilotUtilitySmallModel: utilitySmallModelClean,
    }).catch((e) => console.log("Failed to persist copilot utility models:", e));

    let utilityNote = "";
    try {
      const result = await applyUtilityModelsToVscode(utilityModelClean, utilitySmallModelClean);
      if (!result.applied && result.reason === "unparsable") {
        utilityNote = " Utility models were saved, but settings.json has syntax errors — set chat.utilityModel / chat.utilitySmallModel manually (see Manual Config).";
      }
    } catch (e) {
      console.log("Failed to apply utility models to VS Code settings:", e);
      utilityNote = " Utility models were saved, but VS Code settings.json could not be written — set chat.utilityModel / chat.utilitySmallModel manually (see Manual Config).";
    }

    return NextResponse.json({
      success: true,
      message: `Copilot Custom Endpoint config applied. Reload VS Code to take effect.${utilityNote}`,
      configPath,
    });
  } catch (error) {
    console.log("Error updating copilot settings:", error);
    return NextResponse.json({ error: "Failed to update copilot settings" }, { status: 500 });
  }
}

// DELETE - Remove 9Router entry from chatLanguageModels.json
export async function DELETE() {
  try {
    const configPath = getConfigPath();

    let config = [];
    try {
      const existing = await fs.readFile(configPath, "utf-8");
      const parsed = JSON.parse(existing);
      config = Array.isArray(parsed) ? parsed : [];
    } catch (error) {
      if (error.code === "ENOENT") {
        return NextResponse.json({ success: true, message: "No config file to reset" });
      }
      throw error;
    }

    config = config.filter((e) => e.name !== "9Router");
    await fs.writeFile(configPath, JSON.stringify(config, null, 2));

    // Best-effort: drop the utility-model overrides from VS Code settings + DB so
    // a reset fully reverts to Copilot's built-in utility model.
    await updateSettings({ copilotUtilityModel: "", copilotUtilitySmallModel: "" }).catch(() => {});
    await applyUtilityModelsToVscode("", "").catch((e) => console.log("Failed to clear utility models from VS Code settings:", e));

    return NextResponse.json({
      success: true,
      message: "9Router removed from Copilot config",
    });
  } catch (error) {
    console.log("Error resetting copilot settings:", error);
    return NextResponse.json({ error: "Failed to reset copilot settings" }, { status: 500 });
  }
}
