import { build } from 'esbuild';
import { builtinModules } from 'node:module';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const apiRoot = join(root, 'src/app/api');

async function routes(directory = apiRoot) {
  const entries = await readdir(directory, { withFileTypes: true });
  const found = await Promise.all(entries.map(async (entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return routes(path);
    return entry.name === 'route.js' ? [path] : [];
  }));
  return found.flat();
}

const files = (await routes()).sort();
const manifest = `// Generated by scripts/build-server.mjs. Do not edit.\nexport const routeModules = [\n${files.map((file) => {
  const sourceFile = relative(root, file).replaceAll('\\', '/');
  const relativeDirectory = relative(apiRoot, dirname(file)).replaceAll('\\', '/');
  const pathname = relativeDirectory ? `/api/${relativeDirectory}` : '/api';
  return `  { file: ${JSON.stringify(sourceFile)}, pathname: ${JSON.stringify(pathname || '/')}, load: () => import(${JSON.stringify(`../${sourceFile}`)}) },`;
}).join('\n')}\n];\n`;
await writeFile(join(root, 'server/route-manifest.js'), manifest);

await mkdir(join(root, 'dist-server'), { recursive: true });
const buildResult = await build({
  entryPoints: [join(root, 'server/start.js')],
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  outfile: join(root, 'dist-server/index.js'),
  sourcemap: true,
  metafile: true,
  packages: 'external',
  banner: {
    js: "import { createRequire as __createRequire } from 'node:module'; import { fileURLToPath as __fileURLToPath } from 'node:url'; import { dirname as __pathDirname } from 'node:path'; const require = __createRequire(import.meta.url); const __filename = __fileURLToPath(import.meta.url); const __dirname = __pathDirname(__filename);",
  },
  alias: {
    '@': join(root, 'src'),
    'next/server': join(root, 'server/compat/next-server.js'),
    'next/headers': join(root, 'server/compat/next-headers.js'),
  },
});
await writeFile(join(root, 'dist-server/package.json'), '{"type":"module"}\n');
const rootPackage = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
const packageName = (specifier) => specifier.startsWith('@')
  ? specifier.split('/').slice(0, 2).join('/')
  : specifier.split('/')[0];
const externalPackages = new Set();
const builtins = new Set([...builtinModules, ...builtinModules.map((name) => `node:${name}`)]);
for (const output of Object.values(buildResult.metafile.outputs)) {
  for (const imported of output.imports || []) {
    if (imported.external && !builtins.has(imported.path) && !imported.path.startsWith('node:') && !imported.path.startsWith('bun:')) {
      externalPackages.add(packageName(imported.path));
    }
  }
}
const runtimeDependencies = Object.fromEntries([...externalPackages].sort().map((name) => {
  const version = rootPackage.dependencies?.[name] || rootPackage.optionalDependencies?.[name];
  if (!version) throw new Error(`Missing runtime dependency declaration for ${name}`);
  return [name, version];
}));
await writeFile(join(root, 'dist-server/runtime-dependencies.json'), `${JSON.stringify(runtimeDependencies, null, 2)}\n`);
